# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Hana Dampf's website for sharing fun results with colleagues
tagline:             ''
description:         'Hana Dampf, M.Sc'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hana Dampf
  email:             hana.dampf@mail.utoronto.ca

# Custom vars
version:             1.0.0
