# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Hana Dampf
tagline:             ''
description:         'My personal website for sharing fun results with colleagues'
url:                 http://www.hana-dampf.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hana Dampf
  email:             hana.dampf@mail.utoronto.ca

# Custom vars
version:             1.0.0
